name: 'Slack Notify - DataMa'
description: 'This action will send a notification to Slack'
author: 'django-datama'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/django-datama/action-slack-notify:v2.2.0'
branding:
  icon: 'bell'
  color: 'green'
